routes/web.php
<?php

// Home
Route::get('/', 'HomeController')->name('home');

// Language
Route::get('language/{lang}', 'LanguageController')
    ->where('lang', implode('|', config('app.languages')));

// Admin
Route::get('admin', 'AdminController')->name('admin');

// Medias
Route::get('medias', 'FilemanagerController')->name('medias');

// Blog 
Route::get('blog/tag', 'BlogFrontController@tag');
Route::get('blog/search', 'BlogFrontController@search');
Route::get('articles', 'BlogFrontController@index');
Route::get('blog/order', 'BlogController@indexOrder')->name('blog.order');
Route::resource('blog', 'BlogController', ['except' => 'show']);
Route::put('postseen/{id}', 'BlogAjaxController@updateSeen');
Route::put('postactive/{id}', 'BlogAjaxController@updateActive');
Route::get('blog/{blog}', 'BlogFrontController@show')->name('blog.show');

// Comment
Route::resource('comment', 'CommentController', [
    'except' => ['create', 'show', 'update']
]);
Route::put('comment/{comment}', 'CommentAjaxController@update')->name('comment.update');
Route::put('commentseen/{id}', 'CommentAjaxController@updateSeen');

// Contact
Route::resource('contact', 'ContactController', ['except' => ['show', 'edit']]);

// Roles
Route::get('roles', 'RoleController@edit');
Route::post('roles', 'RoleController@update');

// Users
Route::get('user/sort/{role?}', 'UserController@index');
Route::get('user/blog-report', 'UserController@blogReport')->name('user.blog.report');
Route::resource('user', 'UserController', ['except' => 'index']);
Route::put('uservalid/{id}', 'UserAjaxController@valid');
Route::put('userseen/{user}', 'UserAjaxController@updateSeen');

// Authentication 
Auth::routes();

// Email confirmation 
Route::get('resend', 'Auth\RegisterController@resend');
Route::get('confirm/{token}', 'Auth\RegisterController@confirm');

// Notifications
Route::get('notifications/{user}', 'NotificationController@index');
Route::put('notifications/{notification}', 'NotificationController@update');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\ResetPassword as ResetPasswordNotification;
use App\Notifications\ConfirmEmail as ConfirmEmailNotification;
use App\Models\Role;
use App\Models\Post;
use App\Models\Comment;
use Storage;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    /**
     * One to Many relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    /**
     * One to Many relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     * One to Many relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
    
    /**
     * Send the email verification notification.
     *
     * @param  string  $confirmation_code
     * @return void
     */
    public function sendConfirmEmailNotification($confirmation_code)
    {
        $this->notify(new ConfirmEmailNotification($confirmation_code));
    }

    /**
     * Get user statut
     *
     * @return string
     */
    public function getStatut()
    {
        return $this->role->slug;
    }

    /**
     * Get user files directory
     *
     * @return string|null
     */
    public function getFilesDirectory()
    {
        if ($this->role->slug == 'redac') {
            $folderPath = 'user' . $this->id;
            if (!in_array($folderPath , Storage::disk('files')->directories())) {
                Storage::disk('files')->makeDirectory($folderPath);
            }
            return $folderPath;
        }
        return null;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use App\Repositories\RoleRepository;
use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Requests\RoleRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * The UserRepository instance.
     *
     * @var \App\Repositories\UserRepository
     */
    protected $userRepository;

    /**
     * The RoleRepository instance.
     *
     * @var \App\Repositories\RoleRepository
     */
    protected $roleRepository;

    /**
     * Create a new UserController instance.
     *
     * @param  \App\Repositories\UserRepository $userRepository
     
     * @return void
     */
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;

        $this->middleware('admin');
    }

    /**
     * Display a listing users.
     * 
     * @param  \App\Repositories\RoleRepository $roleRepository
     * @param  string  $role
     * @return \Illuminate\Http\Response
     */
    public function index(RoleRepository $roleRepository, $role = 'total')
    {
        $users = $this->userRepository->getUsersWithRole(config('app.nbrPages.back.users'), $role);
        $counts = $this->userRepository->counts();
        $roles = $roleRepository->all();

        return view('back.users.index', compact('users', 'counts', 'roles'));
    }

    /**
     * Show the form for creating a new user.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('back.users.create');
    }

    /**
     * Store a newly created user in storage.
     *
     * @param  \App\requests\UserCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(UserCreateRequest $request)
    {
        $this->userRepository->store($request->all());

        return redirect('user/sort')->with('ok', trans('back/users.created'));
    }

    /**
     * Display the specified user.
     *
     * @param  \App\Models\User
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('back.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified user.
     *
     * @param  \App\Models\User
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('back.users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage.
     *
     * @param  \App\requests\UserUpdateRequest $request
     * @param  \App\Models\User
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $this->userRepository->update($request->all(), $user);

        return redirect('user/sort')->with('ok', trans('back/users.updated'));
    }

    /**
     * Remove the specified user from storage.
     *
     * @param  \App\Models\user $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->userRepository->destroyUser($user);

        return redirect('user/sort')->with('ok', trans('back/users.destroyed'));
    }

    /**
     * Show the reports of Blog authors, their number of blogs,
     * and the date and title of their latest blog entry.
     *
     * @return \Illuminate\Http\Response
     */
    public function blogReport()
    {
        $authors = $this->userRepository->getBlogAuthorReport();

        return view('back.users.blog_report', compact('authors'));
    }
}

resources/views/back/users/blog_report.blade.php
@extends('back.template')

@section('main')

  @include('back.partials.entete', ['title' => trans('back/admin.blog-report'), 'icon' => 'user', 'fil' => link_to('user/sort', trans('back/users.Users')) . ' / ' . trans('back/admin.blog-report')])

  <div class="row col-lg-12">
    <div class="table-responsive">
      <table class="table">
        <thead>
            <tr>
                <th>{{ trans('back/users.name') }}</th>
                <th>{{ trans('back/users.latest-blog-title') }}</th>
                <th>{{ trans('back/users.posts-count') }}</th>
                <th>{{ trans('back/users.latest-blog-date') }}</th>
            </tr>
        </thead>
        <tbody>
          @foreach ($authors as $author)
            <tr>
                <td class="text-primary">
                    <strong>{{ $author->username }}</strong>
                </td>
                <td>{{ $author->posts->first()->title }}</td>
                <td>{{ $author->posts_count }}</td>
                <td>{{ $author->posts->first()->created_at }}</td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>

@endsection

resources/views/back/users/create.blade.php
@extends('back.template')

@section('main')

    @include('back.partials.entete', ['title' => trans('back/users.dashboard'), 'icon' => 'user', 'fil' => link_to('user/sort', trans('back/users.Users')) . ' / ' . trans('back/users.creation')])

    <div class="col-sm-12">
        {!! Form::open(['url' => 'user', 'method' => 'post', 'class' => 'form-horizontal panel']) !!}   
            {!! Form::controlBootstrap('text', 0, 'username', $errors, trans('back/users.name')) !!}
            {!! Form::controlBootstrap('email', 0, 'email', $errors, trans('back/users.email')) !!}
            {!! Form::controlBootstrap('password', 0, 'password', $errors, trans('back/users.password')) !!}
            {!! Form::controlBootstrap('password', 0, 'password_confirmation', $errors, trans('back/users.confirm-password')) !!}
            {!! Form::selectBootstrap('role', $select, null, trans('back/users.role')) !!}
            {!! Form::submitBootstrap(trans('front/form.send')) !!}
        {!! Form::close() !!}
    </div>

@endsection

resources/views/back/users/edit.blade.php
@extends('back.template')

@section('main')

    @include('back.partials.entete', ['title' => trans('back/users.dashboard'), 'icon' => 'user', 'fil' => link_to('user/sort', trans('back/users.Users')) . ' / ' . trans('back/users.edition')])

    <div class="col-sm-12">
        {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put', 'class' => 'form-horizontal panel']) !!}
            {!! Form::controlBootstrap('text', 0, 'username', $errors, trans('back/users.name')) !!}
            {!! Form::controlBootstrap('email', 0, 'email', $errors, trans('back/users.email')) !!}
            {!! Form::selectBootstrap('role', $select, $user->role_id, trans('back/users.role')) !!}
            {!! Form::checkboxHorizontalBootstrap('confirmed', trans('back/users.confirmed'), $user->confirmed) !!}
            {!! Form::submitBootstrap(trans('front/form.send')) !!}
        {!! Form::close() !!}
    </div>

@endsection

resources/views/back/users/index.blade.php
@extends('back.template')

@section('head')

    <style type="text/css">

        .badge {
            padding: 1px 8px 1px;
            background-color: #aaa !important;
        }

    </style>

@endsection

@section('main')

    @include('back.partials.entete', ['title' => trans('back/users.dashboard') . link_to_route('user.create', trans('back/users.add'), [], ['class' => 'btn btn-info pull-right']), 'icon' => 'user', 'fil' => trans('back/users.users')])

    @if(session()->has('ok'))
        @include('partials/error', ['type' => 'success', 'message' => session('ok')])
    @endif

    <div id="tri" class="btn-group btn-group-sm">
        <a href="{!! url('user/sort') !!}" role="button" class="btn btn-default {{ classActiveOnlyPath('user') }}">{{ trans('back/users.all') }} 
            <span class="badge">{{  $counts['total'] }}</span>
        </a>
        @foreach ($roles as $role)
            <a href="{!! url('user/sort/' . $role->slug) !!}" role="button" class="btn btn-default {{ classActiveOnlySegment(3, $role->slug) }}">{{ $role->title . 's' }} 
                <span class="badge">{{ $counts[$role->slug] }}</span>
            </a>
        @endforeach
    </div>

    <div class="pull-right link">{!! $users->links() !!}</div>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>{{ trans('back/users.name') }}</th>
                    <th>{{ trans('back/users.role') }}</th>
                    <th>{{ trans('back/users.seen') }}</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @include('back.users.table')
            </tbody>
        </table>
    </div>

    <div class="pull-right link">{!! $users->links() !!}</div>

@endsection

@section('scripts')

    <script>

        $(function() {
            // Seen gestion
            $(document).on('change', ':checkbox', function() {
                $(this).parents('tr').toggleClass('warning');
                $(this).hide().parent().append('<i class="fa fa-refresh fa-spin"></i>');
                $.ajax({
                    url: '{!! url('userseen') !!}' + '/' + this.value,
                    type: 'PUT',
                    data: "seen=" + this.checked
                })
                .done(function() {
                    $('.fa-spin').remove();
                    $('input[type="checkbox"]:hidden').show();
                })
                .fail(function() {
                    $('.fa-spin').remove();
                    var chk = $('input[type="checkbox"]:hidden');
                    chk.show().prop('checked', chk.is(':checked') ? null:'checked').parents('tr').toggleClass('warning');
                    alert('{{ trans('back/users.fail') }}');
                });
            });
        });

    </script>

@endsection

resources/views/back/users/roles.blade.php
@extends('back.template')

@section('main')

  @include('back.partials.entete', ['title' => trans('back/roles.dashboard'), 'icon' => 'user', 'fil' => link_to('user/sort', trans('back/users.Users')) . ' / ' . trans('back/roles.roles')])

    <div class="col-sm-12">
        @if(session()->has('ok'))
            @include('partials/error', ['type' => 'success', 'message' => session('ok')])
        @endif
        {!! Form::open(['url' => 'roles', 'method' => 'post', 'class' => 'form-horizontal panel']) !!} 
            @foreach ($roles as $role) 
                {!! Form::controlBootstrap('text', 0, $role->slug, $errors, trans('back/roles.' . $role->slug), $role->title) !!}
            @endforeach
            {!! Form::submitBootstrap(trans('front/form.send')) !!}
        {!! Form::close() !!}
    </div>

@endsection

resources/views/back/users/show.blade.php
@extends('back.template')

@section('main')

    @include('back.partials.entete', ['title' => trans('back/users.dashboard'), 'icon' => 'user', 'fil' => link_to('user/sort', trans('back/users.Users')) . ' / ' . trans('back/users.card')])

    <p>{{ trans('back/users.name') . ' : ' .  $user->username }}</p>
    <p>{{ trans('back/users.email') . ' : ' .  $user->email }}</p>
    <p>{{ trans('back/users.role') . ' : ' .  $user->role->title }}</p>
    <p>{{ $user->confirmed ? trans('back/users.confirmed') : trans('back/users.not-confirmed') }}</p>

@endsection

resources/views/back/users/table.blade.php
@foreach ($users as $user)
    <tr {!! !$user->seen? 'class="warning"' : '' !!}>
        <td class="text-primary"><strong>{{ $user->username }}</strong></td>
        <td>{{ $user->role->title }}</td>
        <td>{!! Form::checkbox('seen', $user->id, $user->seen) !!}</td>
        <td>{!! link_to_route('user.show', trans('back/users.see'), [$user->id], ['class' => 'btn btn-success btn-block btn']) !!}</td>
        <td>{!! link_to_route('user.edit', trans('back/users.edit'), [$user->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
        <td>
            {!! Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) !!}
                {!! Form::destroyBootstrap(trans('back/users.destroy'), trans('back/users.destroy-warning')) !!}
            {!! Form::close() !!}
        </td>
    </tr>
@endforeach